# Generated by Django 4.1.7 on 2023-05-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_question_correctoption_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
