# Generated by Django 4.1.7 on 2023-05-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_quiz_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='status',
        ),
    ]
